INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (201, N'Chicken Biryani', N'NonVeg', 200, N'For Two', N'biryani.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (201, N'Chicke Lolipop', N'NonVeg', 100, N'For One', N'chicken-lollipop.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (201, N'Chicken 65', N'NonVeg', 90, N'For One', N'picture1.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (201, N'Pizza', N'Snacks', 150, N'For One', N'picture2.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (201, N'Coke', N'Drink', 50, N'For One', N'coke.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (202, N'Fried Rice', N'Veg', 200, N'For Two', N'veg.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (202, N'Chicken Kabab', N'NonVeg', 100, N'For One', N'kabab.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (202, N'Burger', N'NonVeg', 100, N'For One', N'burger.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (202, N'Coke,Burger', N'Veg', 150, N'For One', N'cb.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (202, N'Chicken Manchuria', N'NonVeg', 90, N'For One', N'chicman.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (206, N'Manchuria', N'Veg', 180, N'For Two', N'vegman.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (207, N'Pizza', N'Snacks', 100, N'For Two', N'picture2.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (207, N'Pepsi', N'Snacks', 80, N'For One', N'pepsi.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (211, N'Cool Cake', N'Snacks', 60, N'Two Pieces', N'cake.jpg', 1)
INSERT INTO [dbo].[FoodItemsListData] ([Rid], [ItemName], [ItemType], [Price], [Quantity], [ImageUrl], [Plate]) VALUES (212, N'Ice Cream ButterSkotch', N'Snacks', 180, N'Family Pack', N'ice.jpg', 1)
