INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Pizza Hut', N'Veg', N'Chicken Lolipop', N'Charge', 130, 20)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Pizza Hut ', N'NonVeg', N'Chicken Biryani', N'Charge', 140, 30)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Hyderabad Hosts', N'Veg', N'Fried Rice', N'Free', 100, 0)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Hyderabad Hosts', N'NonVeg', N'Mutton Kima', N'Charge', 200, 40)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Dominos', N'Veg', N'Pizza', N'Charge', 130, 30)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Dominos', N'NonVeg', N'Pizza', N'Free', 200, 0)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Qube Cafe', N'Veg', N'Parota', N'Charge', 40, 20)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Qube Cafe', N'NonVeg', N'Chicken 65', N'Free', 90, 0)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Qube Cafe', N'Veg', N'Manchuria', N'Free', 90, 0)
INSERT INTO [dbo].[Category] ([RestaurantName], [Category], [Item Type], [Delivery type], [Price], [Delivery Charge]) VALUES (N'Qube Cafe', N'NonVeg', N'Chicken Rolls', N'Charge', 100, 30)
