INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (1, N'Qube Cafe', N'Chicken Biryani', N'NonVeg', N'Charge', 180, N'30')
INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (2, N'Qube Cafe', N'Chicken Rolls', N'NonVeg', N'Charge', 90, N'30')
INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (4, N'Dominos', N'Pizza', N'NonVeg', N'Charge', 180, N'30')
INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (5, N'Qube Cafe', N'Prawns Biryani', N'NonVeg', N'Free', 180, N'0')
INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (6, N'Hyderabad Hosts', N'Chicken 65', N'NonVeg', N'Charge', 90, N'40')
INSERT INTO [dbo].[Foodies] ([Id], [RestaurantName], [ItemType], [Category], [Deliverytype], [Price], [DeliveryCharge]) VALUES (8, N'Akbar Court', N'Chicken Biryani', N'NonVeg', N'Charge', 180, N'30')
